### ISSUE TITLE
ESP32 / Hardware serial

### ISSUE THREAD

**Issue by Onno-Dirkzwager** [Nredor/ESPNexUpload#1]
Hi Nredor,
are you planning to maintain this library? If so, would you be interested in a Pull request regarding the esp32?

Ive modified your version to use software serial for the esp8266 and hardware serial for the esp32.

**Comment by NNMavy** [comment]
I am looking into doing the same with my ESP32 and Screen. Would it be possible to share your modified version?

**Comment by NNMavy** [comment]
Awesome news, if you need any help testing let me know.

On a side note, the latest arduino core for esp (2.4.2) has a bug with spiffs causing a wdt reset. This should be fixed in 2.5.0 as mentioned in https://github.com/esp8266/Arduino/issues/5242

**Comment by Onno-Dirkzwager** [comment]
@NNMavy 
I still have to do some finetuning in the httpclient example before making a official pull request, but for the rest it works! Maby you can help by doing some tests?

https://github.com/Onno-Dirkzwager/ESPNexUpload

**Comment by NNMavy** [comment]
@Onno-Dirkzwager
Thanks for sharing, I will see if I can test it today.

**Comment by NNMavy** [comment]
@Onno-Dirkzwager I am running into the issue that I cannot upload any form of tft file as they appear to be getting corrupt during the upload. I have also noticed this same behavior with the default upload library. 

@Nredor or @Onno-Dirkzwager are you aware of any form of crc build into the tft file at compile? I have gone over the nextion docs several times but cannot find any mention to this.

**Comment by Onno-Dirkzwager** [comment]
@NNMavy I ran into something simelar and have updated my fork yesterday. Are you running this most recent version?

**Comment by NNMavy** [comment]
I seem to have run into a new issue with both (SPIFFS & direct) versions of the library. For what ever reason my ESP is missing data when sending the file to the display.

The file size the display expects gets send correctly, but the display will sit at 90% even tho the esp thinks all the data has already been send. I have a feeling it is something in the webserver code as that is the only common part between the 2 that could cause the same issue on both ways of sending the file.

**Comment by Onno-Dirkzwager** [comment]
@NNMavy so you run into this problem with both the original and my modified version of the library?

**Comment by abs-zero-ian** [comment]
Interesting problem, as I have been testing a possibly older version of
Onno's modified library.  All I've done is disable the file size check once
SPIFFS wasn't being used and have seen that work perfectly since.  Is it
possible your ESP is trying to do something else at the same time as update
the display?

**Comment by NNMavy** [comment]
@abs-zero-ian hit the nail in the head. I forgot to turn of some of the background tasks to update some DHT sensors. Stopping those before running the update fixed the issue and I can now update my display without any issues. My guess is that the dual core capabilities are throwing the webserver tasks of track.

**Comment by Nredor** [comment]
> Hi Nredor,
> are you planning to maintain this library? If so, would you be interested in a Pull request regarding the esp32?
> 
> Ive modified your version to use software serial for the esp8266 and hardware serial for the esp32.

Absolutely 👍 I'll review the pull request as soon as you have time to submit. Seems that your upgrades are working at least for 2 testers and I'll test the esp8266 part asap.

**Comment by Nredor** [comment]
> @abs-zero-ian hit the nail in the head. I forgot to turn of some of the background tasks to update some DHT sensors. Stopping those before running the update fixed the issue and I can now update my display without any issues. My guess is that the dual core capabilities are throwing the webserver tasks of track.

We'll have to add some note about that in the documentation

**Comment by Onno-Dirkzwager** [comment]
@Nredor Thanks I hope to send the pull request tonight! Just cleaning the code and removing previous attempts.

**Comment by Onno-Dirkzwager** [comment]
@Nredor I finaly made the pull request. I had some more delays. I realised to late that I was still using the beta releases for the new 32 core and had to change some things in the examples for the current core release.

@NNMavy & @abs-zero-ian if you guys are in for an other test round please update your code: https://github.com/Onno-Dirkzwager/ESPNexUpload

**Comment by abs-zero-ian** [comment]
Happy New Year @Onno-Dirkzwager @NNMavy @Nredor 

I've tested this using 8266 (Sketch compiled using a freshly cloned nextion-beta branch of https://github.com/iotappstory/ESP-Library and Onno's version https://github.com/Onno-Dirkzwager/ESPNexUpload )

That works fine for me, no issues whatsoever.  I'll now pull the ESP8266 and put the ESP32 in (probably a job for tomorrow morning!

**Comment by Nredor** [comment]
Excellent. I actually don't have time to test esp8266 so good that you did that. I'll just review the code and accept the pull request as is.
 
Thanks all!

**Comment by Onno-Dirkzwager** [comment]
@NNMavy @abs-zero-ian,
@Nredor accepted my pull request and it can now be found in the Arduino library manager.
Thanks for testing, Im closing this issue.
