### ISSUE TITLE
Error in connection with Nextion display

### ISSUE THREAD

**Issue by BhupendraTech** [Nredor/ESPNexUpload#15]
Hi  @Nredor and everyone there!

I tried the WiFiClient example to download and flash a .tft file to my Nextion display using this library with NodeMCU ESP8266 board. While the .tft downloads successfully to NodeMCU, I receive an **error in getting the baudrate** of Nextion display sometimes, and sometimes I see the **"Error: handling sleep and dim settings failed"**. Also sometimes the NodeMCU watchdog resets. The purpose I want to achieve is to be able to update the display's .tft files over the air.

The Nextion display model I am trying with is **"NX8048P070-011C"** and the connections between NodeMCU and Nextion display are made as mentioned in src file "ESPNexUpload.cpp". Also I tried by modifying the "this->sendCommand()" parameters by adding the "ÿ" characters in postfix and prefix wherever required as suggested in one of the issues [here](https://github.com/Nredor/ESPNexUpload/issues/5#issuecomment-498028131) but still no luck. I am pretty new in handling Nextion display, so any help or suggestions would be highly helpful and appreciated. I am attaching the serial monitor logs I captured with two displays of same model, please refer and help.

Thanks in advance,
Regards,
Bhupendra.
[Display1-WiFiClient-Logs.txt](https://github.com/Nredor/ESPNexUpload/files/5609770/Display1-WiFiClient-Logs.txt)
[Display2-WiFiClient-Logs.txt](https://github.com/Nredor/ESPNexUpload/files/5609772/Display2-WiFiClient-Logs.txt)

**Comment by alperssl** [comment]
Hi, I had the same issue with NX4832K035 today. And find a quick solution for this problem.
You can add
```
while(response[0] == 0xFF){
	response = response.substring(1, response.length());
}
```
right after line 492 and 511 in ESPNexUpload.cpp
