### ISSUE TITLE
Cannot compile for LOLIN 32 

### ISSUE THREAD

**Issue by gcharles81** [Nredor/ESPNexUpload#3]
This is the compiler error I am getting on arduino IDE whel I compile the upload example 

UploadServer:100:22: error: 'class ESPNexUpload' has no member named 'prepairUpload'
result = nextion.prepairUpload(fileSize);

Thanks

**Comment by Onno-Dirkzwager** [comment]
Hi @gcharles81,
there is a typo in the upload example:
prepairUpload should be prepareUpload
If you change this yourself it will compile whithout problems.

This probably happend in my last pull request. Ill send @Nredor a new pull request to fix this. Our apologies for the hassle.

**Comment by Onno-Dirkzwager** [comment]
@gcharles81
https://github.com/Nredor/ESPNexUpload/pull/4/files
