### ISSUE TITLE
Unable to upload to NX4832K035_011

### ISSUE THREAD

**Issue by makeSmartio** [Nredor/ESPNexUpload#5]
I am using the WifiClient example and and have edited the ssid, password, host, and url for an ESP32 Dev Board. The code works great for my 2.4" NX3224K024_011 but fails with the 3.5"
NX4832K035_011 with the following error (yes, I am using a compatible tft file.)
connecting to example.com
Requesting URL: /Nextion.tft
File received. Update Nextion...
Error: get baudrate error
Closing connection

If I use an SD card it works, and I can access the screen via serial from the ESP32. 

What is different for the 3.5"? I even ordered a 2nd 3.5" and got the same result.

**Comment by Onno-Dirkzwager** [comment]
Hi @makeSmartio,
have you tried lowering the baudrate?
And how is serial communication in general? Have you been able to send other commands to your nextion?

**Comment by makeSmartio** [comment]
Yes, I tried 9600. Same result.

**Comment by Onno-Dirkzwager** [comment]
Unfortunately I can't be of direct help. I only have an 2.4 and will order an 3.5 to reproduce your problem. For whatever reason the updater cannot reach the Nextion even thought you already proved serial communication is posible with your ESP32.

Which 3.5 do you have? The basic or Enhanced?

**Comment by makeSmartio** [comment]
Enhanced. I know, it is a crazy thing. I might try the non-enhanced instead. Thanks for your help!

**Comment by Onno-Dirkzwager** [comment]
Im under the impression that you never reach this point but it might be worth experimenting with the [delay](https://github.com/Nredor/ESPNexUpload/blob/master/src/ESPNexUpload.cpp#L223)

We used 50 as an avarage as this seems to work well with the basic versions. But as mentioned in these [nextion protocol docs](https://nextion.itead.cc/2017/12/08/nextion-hmi-upload-protocol-v1-1/) you might need a different value.

**Comment by makeSmartio** [comment]
I adjusted the delay to 500 and 5000 - it made no difference. 
I added some debug output to

```
bool ESPNexUpload::_searchBaudrate(uint32_t baudrate){
	
    #if defined ESP8266
        yield();
    #endif
	delay(50);
    String string = String("");  
    nexSerialBegin(baudrate);
	dbSerialPrintln(baudrate);
    this->sendCommand("");
    this->sendCommand("connect");
    this->recvRetString(string);
    dbSerialPrintln(string);
    if(string.indexOf(F("comok")) != -1){
        return 1;
    } 
    return 0;
}
```


Output of 3.5":

```
F⸮Serial tests & connect
_getBaudrate
115200

19200

9600
⸮⸮⸮⸮⸮⸮
57600

38400

4800

2400
```


Output of 2.4":

```
F⸮Serial tests & connect
_getBaudrate
115200

19200

9600
⸮⸮⸮comok 1,30601-0,NX3224K024_011R,99,61489,E4686CC347171124,16777216⸮⸮⸮
get baudrate
whmi-wri 1509902,115200,0
Changing baudrate...
115200
```

Does this help?

**Comment by makeSmartio** [comment]
I think I figured it out. I changed the connect string to:
this->sendCommand("connectÿÿÿ");
It still took multiple passes to get in though. Still testing.

**Comment by Onno-Dirkzwager** [comment]
@makeSmartio 
Glad to see you took the challange! Im interested in what your findings are.

**Comment by makeSmartio** [comment]
Testing on both the 2.4" Enhanced and 3.5" Enhanced both are working well with these connection strings:
```
    this->sendCommand("DRAKJHSUYDGBNCJHGJKSHBDNÿÿÿ");
    this->sendCommand("connectÿÿÿ");
    this->sendCommand("ÿÿconnectÿÿÿ");
```

Thanks again for your help!

**Comment by Onno-Dirkzwager** [comment]
@makeSmartio that's great news!
- Do you think this is a basic vs enhanced difference?
- Would you be interested in making a pull request with your suggested changes? (It would only be fair to give you the credits...)

**Comment by makeSmartio** [comment]
You work with the Youtube celebrity Andreas?! Nice! I will check it out. 
No, I don't think the difference is the Enhanced thing because both of my displays are Enhanced and the 2.4" worked as is. I will be trying the non-enhanced ones soon and will verify, but I suspect it will work based on the Protocol doc. 
I'd love to try a Pull request - it would be my first!

**Comment by Onno-Dirkzwager** [comment]
Yes it's an honor ;)

I have an basic next to me. If you send me the exact line nr you made de changes (just to be sure) Ill copy your changes and test on the basic 2.4

I think this would make a great first PR!

**Comment by CustomSmartControls** [comment]
Firstly I would like to say a big thank you for the help in this thread, it has assisted me greatly in uploading my tft file to my 3.5" enhanced Nextion screen, however I have not been 100% successful yet; I wanted to ask why it is necessary to use softwareserial for the ESP8266 - I edited the cpp file to use the hardware serial (GPIO1 and 3) on my ESP8266 but as soon as it starts to upload I get an error message on the screen about the file being incompatible for the model of screen I am using (the tft file is perfectly fine and I can upload it via the SD card) - I would have thought that the hardware serial port would have been the first and best option when uploading to the screen. Any advice will be appreciated.

Here is a photo of the error message when  I try use hardware serial
![20220516_233132](https://user-images.githubusercontent.com/105714261/168788664-6cb3880a-d5b8-419d-a819-ed552d9f1bb1.jpg)
