### ISSUE TITLE
Check Data after upload returns error

### ISSUE THREAD

**Issue by joeltbennett** [Nredor/ESPNexUpload#9]
Hi - I have the HTTP get method working fine, it downloads all 8mb of my TFT file, but immediately after receiving the upload (via stream method), the Nextion goes to a Check Data screen, counts up to 100% quickly, then says: "Update Failed: check Error!"

It looks like it's trying to tell me something else, but the text fields being populated are cramped and stuck behind the failure message, so I can't read it - it says: "this is created.....", "1024", "freeed...."

No idea what it means, 1024 only looks familiar as the EEPROM size on the screen. The TFT file is pretty heavy, 8mb with lots of images.

It's an Enhanced 5" Nextion screen connected to an ESP32 WROOM. Baudrate is 115200 for everything. Any thoughts would be greatly appreciated - getting the Nextion screen to update OTA via an http connection would improve my project greatly. Thanks!

**Comment by Nredor** [comment]
Have you tried to upload smaller file? I don't have the enchanced versions of nextion screens but at least some people have them working just fine

**Comment by Nredor** [comment]
I merged enhancements made by Machiel80 so try again after updating the library :)

**Comment by carlback** [comment]
@joeltbennett I have the same issue. How did you solve this? :)

**Comment by joeltbennett** [comment]
I’m really sorry, I wish I could remember - my head hasn’t been in this stuff for a while. I did get it to work though…if that’s any help 💩

**Comment by carlback** [comment]
Thanks for your reply! Then i know that just have to try harder :)

**Comment by MaxVallardi** [comment]
Hi, I had the exact same problem with the same garbage on the screen on a Nextion connected via SoftwareSerial. Once connected to Serial, the same sketch uploaded the .tft file without problem at 115200.
Hope this help somebody...
